
FAIL sending one chunk through a transferred stream should work promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL sending ten chunks through a transferred stream should work promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL sending ten chunks one at a time should work promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL sending ten chunks on demand should work promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL transferring a stream should relieve backpressure promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL transferring a stream should add one chunk to the queue size promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL the extra queue from transferring is counted in chunks promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL cancel should be propagated to the original promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL cancel should abort a pending read() promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL stream cancel should not wait for underlying source cancel promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL serialization should not happen until the value is read promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL transferring a non-serializable chunk should error both sides promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL errors should be passed through promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL race between cancel() and error() should leave sides in different states promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL race between cancel() and close() should be benign promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."
FAIL race between cancel() and enqueue() should be benign promise_test: Unhandled rejection with value: object "DataCloneError: The object can not be cloned."

